name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install || true
          gem install fastlane

      - name: Run iOS Unit/UI Tests
        run: |
          xcodebuild test \
            -workspace SampleLatestApp.xcworkspace \
            -scheme SampleLatestApp \
            -destination 'platform=iOS Simulator,name=iPhone 14'

      - name: Build iOS app
        run: fastlane beta
